### ISSUE TITLE
versions 9.0.5,9.0.6 fail to build on Android API level 28

### ISSUE THREAD

**Issue by avi-mastov** [Instabug/Instabug-Flutter#114]
Output is:
`FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> Android resource linking failed
  /Users/avimastov/StudioProjects/lumen/build/app/intermediates/merged_manifests/debug/AndroidManifest.xml:382: AAPT: error: attribute android:foregroundServiceType not found.

  error: failed processing manifest.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 22s
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
Building plugin audioplayers...
Running Gradle task 'assembleAarRelease'...
✓ Built build/app/outputs/repo.
Building plugin barcode_scan...
Running Gradle task 'assembleAarRelease'...
✓ Built build/app/outputs/repo.
Building plugin barometer...
Running Gradle task 'assembleAarRelease'...
Finished with error: ProcessException: Permission denied
  Command: /Users/avimastov/.pub-cache/git/barometer-6bcbcc4e1a3dccd18947b72f554765dde83948b6/android/gradlew -I=/Users/avimastov/development/flutter/packages/flutter_tools/gradle/aar_init_script.gradle -Pflutter-root=/Users/avimastov/development/flutter -Poutput-dir=/Users/avimastov/StudioProjects/lumen/build/app -Pis-plugin=true -Ptarget-platform=android-arm,android-arm64,android-x64 assembleAarRelease`

The relevant line in `AndroidManifest.xml` is:
`<service
            android:name="com.instabug.library.internal.video.ScreenRecordingService"
            android:enabled="true"
            android:exported="false"
            android:foregroundServiceType="mediaProjection" />`

It complains about `android:foregroundServiceType="mediaProjection"`

**Comment by kushal-rathod1** [comment]
I'm also getting something like this
`FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     /home/rentax/.gradle/caches/transforms-2/files-2.1/a6f6a8006419eabceaaa51d25379bbe3/jetified-instabug-core-9.0.5.0/AndroidManifest.xml:40:9-44:63: AAPT: error: attribute android:foregroundServiceType not found.


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
Building plugin image_gallery_saver...
Running Gradle task 'assembleAarRelease'...
Finished with error: ProcessException: Permission denied
  Command: /home/rentax/SDKs/flutter/.pub-cache/hosted/pub.dartlang.org/image_gallery_saver-1.2.2/android/gradlew -I=/home/rentax/SDKs/flutter/packages/flutter_tools/gradle/aar_init_script.gradle -Pflutter-root=/home/rentax/SDKs/flutter -Poutput-dir=/home/rentax/FlutterApps/EATOS/eo_analytic_app/build/app -Pis-plugin=true -Ptarget-platform=android-arm,android-arm64,android-x64 assembleAarRelease`

**Comment by AliAbdelfattah** [comment]
@avi-mastov @kushal-rathod1 hi guys, please update your android build settings to use Android API level 29 because Instabug now requires it.
