### ISSUE TITLE
Shake invocation not working on Android

### ISSUE THREAD

**Issue by bmthorntn** [Instabug/Instabug-Flutter#250]
### Steps to Reproduce the Problem
1. Integrate Flutter SDK as per instructions for version 11.0.0 listed here: https://pub.dev/packages/instabug_flutter
2. Specify shake (or any invocation other than floatingButton) on start
3. Shake the device

### Expected Behavior
See the "Need help?" dialog appear.

### Actual Behavior
No dialog appears.

### Instabug integration code
Instabug.start('foo', [InvocationEvent.shake]);

### SDK Version
11.0.0

### Flutter, iOS and Android Versions
Flutter version 2.10.5
Dart version 2.16.2
Android SDK version 31.0.0

### Device Model
Pixel 3a (but haven't checked on others)

### Other notes
- I can launch the dialog manually using show()
- InvocationEvent.floatingButton is working. 
- shake on iOS is working as expected.

**Comment by DavidMina96** [comment]
Hi @bmthorntn, 

Thank you for reporting this. Would you please try setting the shaking threshold to a lower value so that the device is more sensitive to shaking using the below API after `Instabug.start`? 

API:
`BugReporting.setShakingThresholdForAndroid(300);`

It could also help to try on different emulators/physical devices. Happy to hear your feedback :)

**Comment by bmthorntn** [comment]
OK, thank you that worked. Wow, so you really have to shake it like crazy to see it show up. I tested it on iOS first and it was a nice gentle shake so I was expecting the same. I've put it down to 100 and it seems reasonable now. Thanks for your help @DavidMina96
