### ISSUE TITLE
Firebase Analytics Instabug Events

### ISSUE THREAD

**Issue by gizemgizg** [Instabug/Instabug-Flutter#252]
Hello, first of all, thank you very much for the package you developed. I am using firebase analytics in my project and Instabug Events are sent. How can I prevent this?

IBGBugVC
IBGPromptContainerVC
IBGPromptVC
IBGThankYouHUDViewController
IBGScreenshotVC

**Comment by TheBuggedYRN** [comment]
Thanks for reporting this issue @gizemgizg!

Unfortunately, this issue is related to Firebase Analytics, due to the [automatic screen tracking](https://firebase.google.com/docs/analytics/screenviews#automatically_track_screens). You can [disable this behavior](https://firebase.google.com/docs/analytics/screenviews#disable_screenview_tracking) if it doesn't contradict with what you are trying to achieve.

**Comment by gizemgizg** [comment]
thank youuu 🙌🏻💙
